#./driver sample_input/allKindsOfThings.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/allKindsOfThings.out
./driver sample_input/arrayReferences.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/arrayReferences.out
./driver sample_input/assignmentSimpleArithOpsExpr.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/assignmentSimpleArithOpsExpr.out
./driver sample_input/assignmentSimpleNegation.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/assignmentSimpleNegation.out
./driver sample_input/assignmentSimpleRelOpsExpr.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/assignmentSimpleRelOpsExpr.out
./driver sample_input/assignmentSimple.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/assignmentSimple.out
./driver sample_input/ifThenElseFalse.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenElseFalse.out
./driver sample_input/ifThenElseNested1.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenElseNested1.out
./driver sample_input/ifThenElseNested2.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenElseNested2.out
./driver sample_input/ifThenElseNested3.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenElseNested3.out
./driver sample_input/ifThenElseNested4.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenElseNested4.out
./driver sample_input/ifThenElseTrue.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenElseTrue.out
./driver sample_input/ifThenFalse.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenFalse.out
./driver sample_input/ifThenTrue.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/ifThenTrue.out
./driver sample_input/justSimpleAndArrayGlobals.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/justSimpleAndArrayGlobals.out
./driver sample_input/justSimpleGlobals.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/justSimpleGlobals.out
#./driver sample_input/multiProcDeclWithCalls.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/multiProcDeclWithCalls.out
#./driver sample_input/nestedProcDeclWithCalls.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/nestedProcDeclWithCalls.out
./driver sample_input/nestedProcDeclWithLocalsNoCalls.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/nestedProcDeclWithLocalsNoCalls.out
./driver sample_input/noGlobalsOrProcs.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/noGlobalsOrProcs.out
./driver sample_input/oneProcDeclNoLocalsNoCalls.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/oneProcDeclNoLocalsNoCalls.out
#./driver sample_input/oneProcDeclWithCall.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/oneProcDeclWithCall.out
./driver sample_input/oneProcDeclWithLocalsNoCalls.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/oneProcDeclWithLocalsNoCalls.out
#./driver sample_input/oneProcDeclWithRecursiveCall.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/oneProcDeclWithRecursiveCall.out
#./driver sample_input/readIndividuals.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/readIndividuals.out
#./driver sample_input/readMultiples.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/readMultiples.out
./driver sample_input/simpleStmtsFromWithinProc.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/simpleStmtsFromWithinProc.out
./driver sample_input/twoProcDeclWithLocalsNoCalls.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/twoProcDeclWithLocalsNoCalls.out
./driver sample_input/whileNestedDeep.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/whileNestedDeep.out
./driver sample_input/whileNested.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/whileNested.out
./driver sample_input/whileSimple.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/whileSimple.out
./driver sample_input/writeConstants.txt > output.oal; ./oal_parser/oalparse output.oal > ./actual_output/writeConstants.out